### ISSUE TITLE
Create A New Note

### ISSUE THREAD

**Issue by martensonbj** [turingschool-projects/1610-remember-5#7]
At the bottom of the `reminders.hbs` template, there should be a button that routes the user to `/reminders/new` where users can create a new reminder.

* The new reminder should have inputs for the title, date, and notes.
* The new reminder should have a button for submitting the new note.
* Pressing the button should submit a new reminder to the database and immediately displays in the reminders list.
**Hot Tip**: There are no tests set up for this user story. So, you’ll have to write an acceptance test.

**Comment by sljohnson32** [comment]
@martensonbj @Tman22 do you know why the PR on this didn't close this issue?

**Comment by martensonbj** [comment]
Looks like the two issues in the log right now are #8 and #9 -- looks like youre trying to close #7 which isnt an existing issue

**Comment by sljohnson32** [comment]
Hmmm....does puting "closes Issue #7" in the title not do the job?

**Comment by martensonbj** [comment]
Hmm not sure what happened here - I'll close it for you
